version: '3.7' # version of docker-compose to use

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gorelekrosnab
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6.1.1-php8.0
    ports:
      - "3000:80"
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: gorelekrosnab
    volumes:
      - ./wp/wp-content/themes/:/var/www/html/wp-content/themes/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp/wp-content/uploads:/var/www/html/wp-content/uploads











